feat: generate hbase ranger policy #101
TOSIT-IO/tdp-getting-started pull request #102
Opened 2022-05-10 16:30 UTC by gonzaloetjo

#### Which issue(s) this PR fixes:

Fixes #101 

#### Additional comments:
- Add creation of tdp_user hbase policies.
- Correct 'test-cluster-deployment' to provide errors. 

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-05-13 09:48 UTC, leopaul36 commented on deploy-users.yml
> +- name: Create Hbase access policies in Ranger
Should be "HBase"

2022-05-13 09:49 UTC, leopaul36 commented on inventory/group_vars/all.yml
> +        conditions: []
No new line at end of file

2022-05-13 09:49 UTC, leopaul36 commented on test-cluster-deployment.yml
> +      - hbase
No new line at end of file

2022-05-13 09:49 UTC, leopaul36 requested changes
Couple changes as stated by the comments otherwise all good !

2022-05-23 08:25 UTC, Nuttymoon approved these changes

2022-05-23 08:50 UTC, merged