fix(livy): remove redundant livy deployments
TOSIT-IO/tdp-getting-started pull request #176
Opened 2022-08-31 12:03 UTC by jusstol

#### Which issue(s) this PR fixes:

Fixes #174 

#### Additional comments:

Simplification of `deploy-all.yml` since livy and livy for spark3 deployments are already included in `deploy-spark.yml` and `deploy-spark3.yml`.

---
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-08-31 12:09 UTC, leopaul36 approved these changes

2022-08-31 12:16 UTC, leopaul36 requested changes
As [stated](https://github.com/TOSIT-IO/tdp-getting-started/issues/174#issuecomment-1232850877) by @gboutry;

> Since we're deploying per service, I think the fix should be to remove the livy deployments from the spark playbooks, and keep the livy playbooks.

2022-09-01 16:59 UTC, gboutry approved these changes

2022-09-07 09:49 UTC, rpignolet commented
@jusstol  thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.

This PR has been validated and will soon be merged to master branch.
Please note that some changes could be made for better integration with TDP.

2022-09-07 09:50 UTC, merged