Refactor users and ranger policies variables with tdp collection playbooks
TOSIT-IO/tdp-getting-started pull request #181
Opened 2022-09-09 11:42 UTC by rpignolet

#### Which issue(s) this PR fixes:

Fixes #180 

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-09-09 11:52 UTC, mehdibn approved these changes

2022-09-10 18:16 UTC, rpignolet commented
Last force push update `tdp-collection` git submodule to have the new utils playbooks used.

2022-09-12 09:55 UTC, gboutry approved these changes

2022-09-14 16:23 UTC, rpignolet commented
Last for push adding documentation about restarting Ranger Usersync when adding new users and remove `deploy-users.yml` playbook.

2022-09-19 08:24 UTC, gboutry requested changes

2022-09-19 08:24 UTC, gboutry commented on README.md
> +When adding users after Ranger Usersync deployment and want to add or update Ranger policies with these new users, you must wait until Ranger Usersync poll users from LDAP or restart the Ranger Users
```suggestion

When adding users following the Ranger Usersync deployment, you will need to add or update Ranger policies including these new users. You must wait for Ranger Usersync to poll users from LDAP or you can restart the Ranger Usersync using the following playbook:
```

2022-09-19 11:41 UTC, rpignolet commented on README.md
> +When adding users after Ranger Usersync deployment and want to add or update Ranger policies with these new users, you must wait until Ranger Usersync poll users from LDAP or restart the Ranger Users
Done in last force push

2022-09-19 11:42 UTC, gboutry approved these changes

2022-09-19 11:46 UTC, merged