feat: update readme
TOSIT-IO/tdp-getting-started pull request #197
Opened 2022-10-07 15:06 UTC by Nuttymoon

#### Which issue(s) this PR fixes:

Fixes `undefined`

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-10-07 15:08 UTC, gboutry approved these changes

2022-10-07 15:10 UTC, Nuttymoon commented
Had missed one `sudo su`

2022-10-07 16:52 UTC, rpignolet requested changes
@Nuttymoon Need a rebase on master.

2022-10-14 09:53 UTC, rpignolet approved these changes

2022-10-14 10:39 UTC, merged