fix: bump tdp-vagrant to latest version
TOSIT-IO/tdp-getting-started pull request #198
Opened 2022-10-07 15:41 UTC by leopaul36

#### Which issue(s) this PR fixes:

Fixes #196 

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2022-10-07 15:42 UTC, gboutry approved these changes

2022-10-07 16:51 UTC, rpignolet requested changes
@leopaul36 need a rebase on master.

2022-10-10 12:30 UTC, leopaul36 commented
> @leopaul36 need a rebase on master.

Done

2022-10-10 13:34 UTC, rpignolet approved these changes

2022-10-10 13:35 UTC, merged